/*
 * Copyright (c) 2014 by CDAC Chennai 
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * @File        LocationPojo
 * @Created:    18.11.2013
 * @author:     Rekha
 * Last Change: 9.09.2014 by Prasenjit
 */
package com.contextawareframework.sensors.positionsensors;

/**
 * This is a POJO class for accessing details (property field) of Location  
 * service in Android. It contains the getter and setter for all attributes.
 */

public class LocationPojo {

	// To store Latidue
	private float latitude;

	// To store longitude
	private float longitude;

	// Autogenerated int field used as primary key
	private int id;

	// To store time stamp details
	private long timeStamp;

	// To store Place Name 
	private String placeName;

	// To store Place information
	private String placeInfo;

	/**
	 * public Constructor 
	 */
	public LocationPojo(){

	}
	/**
	 * Methdo to get the placeName
	 * @return placeName
	 */
	public String getPlaceName() {
		return placeName;
	}
	/**
	 * Method to set the "placeName" class attribute
	 * @param placeName
	 */
	public void setPlaceName(String placename) {
		placeName = placename;
	}
	/**
	 * Method to get the placeInfo
	 * @return placeInfo
	 */
	public String getPlaceInfo() {
		return placeInfo;
	}
	/**
	 * Method to set the "placeInfo" class attribute 
	 * @param placeinfo
	 */
	public void setPlaceInfo(String placeinfo) {
		placeInfo = placeinfo;
	}

	/**
	 * Method to get the latitude
	 * @return latitude
	 */
	public float getLatitude() {
		return latitude;
	}
	/**
	 * Method to set the "latitude" class attribute
	 * @param latitude
	 */
	public void setLatitude(float latitude) {
		this.latitude = latitude;
	}
	/**
	 * Method to get the longitude 
	 * @return longitude
	 */
	public float getLongitude() {
		return longitude;
	}
	/**
	 * Method to set the "longitude" class attribute
	 * @param longitude
	 */
	public void setLongitude(float longitude) {
		this.longitude = longitude;
	}
	/**
	 * Method to get the "id" class attribute
	 * @return id
	 */
	public int getId() {
		return id;
	}
	/**
	 * Method to set the "id" class attribute 
	 * @param id
	 */
	public void setId(int id) {
		this.id = id;
	}
	/**
	 * Method to get the timestamp value
	 * @return timestamp
	 */
	public long getTimestamp() {
		return timeStamp;
	}
	/**
	 * Method to set the timestamp value
	 * @param timestamp
	 */
	public void setTimestamp(long timestamp) {
		this.timeStamp = timestamp;
	}

}